### ISSUE TITLE
do contacts ever get marked as "no bulk email" in CiviCRM?

### ISSUE THREAD

**Issue by jtbayly** [veda-consulting/uk.co.vedaconsulting.mailchimp#118]
Can anybody tell me if this extension *ever* marks contacts as "No bulk email" or "Do not email." and under what exact circumstances this will happen? 

I've gotten conflicting reports on this.

Thanks,
-Joseph

(Edited to add the "Do not email" option.)

**Comment by jason-vivid** [comment]
I don't see a "no-bulk email" in Civi.  I do see a "Bulk Mailings?" button.  Below is how Civi defines that if this is what you are referring to.  

"If you are using the CiviMail component to send mailings to contacts, this field provides additional control over which email address is used. By default, CiviMail sends mail to each contact's preferred email address. If the contact has multiple locations, then the preferred email of the primary location is used. However, if the contact prefers to have CiviMail ('bulk') mailings set to an alternate email address - check the 'Use for Bulk Mailings' box next to that email address."

**Comment by jtbayly** [comment]
There is a setting called that in my installation. There is also "do not email." I'd like to know about either one. Here is a screen grab.
![screen shot 2015-01-07 at 7 02 20 pm](https://cloud.githubusercontent.com/assets/210024/5655748/e8be399e-969f-11e4-84a7-ed57de4e9a4c.png)

Oh, and in case it isn't clear, I wasn't talking about the bulk mail setting on the email address that you explained. This is a contact setting.

Thanks,
-Joseph

**Comment by veda-consulting** [comment]
@jtbayly @jason-vivid in civicrm terms the "No Bulk Emails" is effectivey the user opting out of any mass emails from the organisation, the effect being that any emails sent using the bulk emailing options will exclude this contact. The "Do Not Email" applies across the board and will stop any emails going from CiviCRM to the contact, even transactional ones.

We plan to do a fuller write up of the correlation between these options and Mailchimp in the coming week, stay tuned!

**Comment by jason-vivid** [comment]
On our end allowing the MC extension to enable this would not be great due to reasons I addressed in another post.  Briefly, contacts who are unsubscribed from one list only want to be removed from that list and not ALL of our mailings.  Marking do not mail in this case would halt other communications which would foul up our system.  A suggestion I posted earlier which I think would make others happy and get the same functionality would be to have the MC extension push something into the notes that says they were unsubscribed.   This would be beneficial for multiple reasons, but one of those is that when a user unsubscribes from a list the extension removes them from the group.  You can see it in the LOG but average CRM users wouldn't understand that and know that the API fired and removed them off of the list.  Also as the log grows that data gets lost.  CRM users can reference the notes right away and find out when they were removed from the list and how/why.

**Comment by veda-consulting** [comment]
@jason-vivid the latest version has some enhancements to sync immediately when changes are made to avoid contacts being re-subscribed etc. So when a change is made in CiviCRM its immediately pushed up to Mailchimp to avoid the pull from Mailchimp overriding the change. Closing for now, please open if we have some new questions.
